stages:
  - test

test_job:
  stage: test
  image: python:3.12
  variables:
    CICD_TESTING: "true"
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest discover -s sigmarl/tests -p "*.py"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
