stages:
  - test

test_job:
  stage: test
  image: python:3.12-slim
  variables:
    CICD_TESTING: "true"
  cache:
    key: pip-cache
    paths:
      - .cache/pip
  before_script:
    - pip install --upgrade pip
    - pip install --no-cache-dir -r requirements_gitlab.txt
  script:
    - ls -R sigmarl/tests
    - python -m unittest discover -s sigmarl/tests -p "*.py"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
